#!/usr/bin/env bash
# Generate the git_repositories manifest for mac-dev-playbook from repos on disk.
#
# Scans a set of folders for git repos (at most two levels deep), skips wt-*
# worktree checkouts, linked worktrees and repos without a remote, and prints a
# YAML `git_repositories:` list grouped by folder — the shape the
# 'Clone configured git repositories.' task in main.yml expects. Output is
# stdout unless -o FILE is given. Nothing on disk is modified otherwise.
set -euo pipefail

DEFAULT_ROOTS=(
  "$HOME/praxis-loop"
  "$HOME/Development/GitHub"
  "$HOME/active-git"
  "$HOME/sandbox"
  "$HOME/xpow"
  "$HOME/agent-avocado"
)

usage() {
  cat <<EOF
Usage: $(basename "$0") [-o FILE] [ROOT...]

Scan ROOT folders (default: the list below) for git repos and print a YAML
git_repositories manifest for mac-dev-playbook, grouped by folder.

  -o FILE   write the manifest to FILE instead of stdout
  -h        show this help

Default roots:
$(printf '  %s\n' "${DEFAULT_ROOTS[@]}")

Skipped (reported on stderr): folders that do not exist, repos with no remote,
repos outside \$HOME (dest must be \$HOME-relative). Never listed: dirs named
wt-*, linked worktrees (.git is a file), repos nested inside another repo.

Typical use — preview, then write into the private dotfiles clone:
  $(basename "$0")
  $(basename "$0") -o ~/Development/GitHub/dotfiles/repos.yml
EOF
}

warn() { printf 'generate-repo-manifest: %s\n' "$*" >&2; }

# remote_url DIR — print the clone URL for DIR: origin if present, else the
# first remote. Prints nothing (and returns 1) when the repo has no remote.
remote_url() {
  local dir="$1" name
  if git -C "$dir" remote get-url origin 2>/dev/null; then
    return 0
  fi
  name="$(git -C "$dir" remote | head -n 1)"
  [ -n "$name" ] && git -C "$dir" remote get-url "$name"
}

# tilde PATH — print PATH with a leading $HOME replaced by ~.
tilde() {
  case "$1" in
    "$HOME") echo "~" ;;
    "$HOME"/*) echo "~${1#"$HOME"}" ;;
    *) echo "$1" ;;
  esac
}

out_file=""
while getopts ':o:h' opt; do
  case "$opt" in
    o) out_file="$OPTARG" ;;
    h) usage; exit 0 ;;
    :) warn "option -$OPTARG requires an argument"; usage >&2; exit 2 ;;
    \?) warn "unknown option -$OPTARG"; usage >&2; exit 2 ;;
  esac
done
shift $((OPTIND - 1))

# Folders to scan: arguments, else the default set (see NEW-MAC.md, issue #12).
# Missing folders are skipped with a note, so the default list is safe anywhere.
if [ "$#" -gt 0 ]; then
  roots=("$@")
else
  roots=("${DEFAULT_ROOTS[@]}")
fi

# Only write a file when explicitly asked (-o); default is stdout.
if [ -n "$out_file" ]; then
  exec >"$out_file"
fi

cat <<'EOF'
---
# Repo clone manifest for mac-dev-playbook (git_repositories).
# Generated by scripts/generate-repo-manifest.sh from the repos found on disk;
# regenerate rather than hand-edit. Loaded from <dotfiles clone>/repos.yml by
# main.yml and cloned by the 'Clone configured git repositories.' task
# (--tags repos). Cloning pulls only what is on each remote: push everything
# first. dest is relative to $HOME.
EOF
# emit_entries — print the manifest body (group comments + entries) for $roots.
emit_entries() {
  local root repo_dir url
  for root in "${roots[@]}"; do
    if [ ! -d "$root" ]; then
      warn "skipping $(tilde "$root"): not a directory"
      continue
    fi
    echo "  # --- $(tilde "$root") ---"
    # A repo is a directory whose .git is a DIRECTORY; linked worktrees have a
    # .git file and are skipped, as are dirs named wt-* (worktree checkouts).
    # -prune stops descent into a repo once found (no nested repos/submodules).
    # -mindepth 0 so a root that is itself a repo (e.g. a vault) is listed.
    find "$root" -mindepth 0 -maxdepth 2 -type d \
      \( -name 'wt-*' -prune \) -o \
      \( -exec sh -c 'test -d "$1/.git"' _ {} \; -print -prune \) \
      | sort | while IFS= read -r repo_dir; do
        case "$repo_dir" in
          "$HOME"/*) ;;
          *) warn "skipping $repo_dir: not under HOME ($HOME); dest must be HOME-relative"; continue ;;
        esac
        if ! url="$(remote_url "$repo_dir")"; then
          warn "skipping $repo_dir: no remote (hand-copy it if you need it)"
          continue
        fi
        echo "  - repo: $url"
        echo "    dest: ${repo_dir#"$HOME"/}"
      done
  done
}

body="$(emit_entries)"
if printf '%s\n' "$body" | grep -q '^  - repo: '; then
  echo "git_repositories:"
  printf '%s\n' "$body"
else
  # An explicit empty list: a bare 'git_repositories:' is null and would break
  # the clone task's loop.
  echo "git_repositories: []"
fi
